spring:
  datasource:
#    url: jdbc:mariadb://localhost:3306/greenthumb
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 080525

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://plantbase.chm1hhurblp4.ap-northeast-2.rds.amazonaws.com:3306/plant
    username: admin
    password: plant2023

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
