spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greenthumb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 080525
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
